services:
  - type: background-worker
    name: golden-craft-bot
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: GH_TOKEN
        sync: false
      - key: REPO_OWNER
        value: MoDDyDaN
      - key: REPO_NAME
        value: golden-craft-dev
      - key: FILE_PATH
        value: leaderboard.json
      - key: BRANCH
        value: main
      - key: ADMIN_IDS
        value: "5929919876"
      - key: BOT_TOKEN
        sync: false
      - key: GH_TOKEN
        sync: false
    # Небольшой инстанс бесплатно
    instanceType: free